### PR TITLE
Add MongoDB helpers

### PR DESCRIPTION
**Pull request by noinarisak**
@fnkr, I been working with MongoDB lately with c9 and want to share this enhance with your project. Let me know your thoughts.

### CODE REVIEW

**Comment by fnkr** [comment]
@noinarisak Do you really need the mongodb http interface? Because you added the `--rest` parameter and [this is deprecated since mongodb 3.2](https://jira.mongodb.org/browse/DOCS-6882). Also I wonder if there is any reason why mongodb starts in the foreground.

I made a few changes and committed them to master. Please let me know if this is working for you.

**Comment by noinarisak** [comment]
@fnkr, Nope there is no real need for the `--rest` option, It's was probably left on when I was researching on how to get mongodb on c9 workspace from the community.c9.io forum. [This actual post](https://community.c9.io/t/setting-up-mongodb/1717). 

I'm fairly new to mongodb but one benefit of having it running in foreground (more laziness on my part, lack of further researching other options) is retrieving the connection/host information in the initial start of daemon, so I can copy-pasta generated c9 host url into my nodejs app. 

For example:

```
$ mongod --bind_ip=$IP --dbpath=/home/ubuntu/data --nojournal
warning: bind_ip of 0.0.0.0 is unnecessary; listens on all ips by default
2016-08-31T19:31:16.797+0000 [initandlisten] MongoDB starting : pid=62459 port=27017 dbpath=/home/ubuntu/data 64-bit host=noinarisak-carecenter-api-3350711
```

In the above example `host=noinarisak-carecenter-api-3350711` is basic what I need. If you happen to know another way, I'm open to it. One option, I'm not crazy about this option, is manually building the hosting information from c9 env: `$C9_USER`, `$C9_PROJECT` and `$C9_PID` and echo it out in mongodb-start. Mongod just magically does this for us.

I agree that mongod daemon should be in the background.

Overall, I like your touch up to my PR and will be testing your update. 

Thanks for your input!

**Comment by fnkr** [comment]
@noinarisak I wonder why you need the hostname in order to connect to the MongoDB instance. Can't you just connect to localhost/127.0.0.1?

Anyway, if you just need the hostname you can also get it by executing the command `hostname` (`/bin/hostname`) or by reading the contents of your `/etc/hostname` file.

**Comment by noinarisak** [comment]
@fnkr, how embarrassing, you are totally right. Talk about over thinking it. :) 

Thanks for mentioning `hostname`, it's probably going to be useful on my c9 journey. 

Btw, I validated your changes to my PR. 👍  Thanks again for putting this project together!

**Pull request closed without merging**
